name: ci

on:
    pull_request:
      branches: [ develop ]
    push:
      branches: [ master, develop ]
      tags:
        - v*

jobs:
    quality:
      uses: ./.github/workflows/quality.yml
    test:
      uses: ./.github/workflows/test.yml
      needs: [quality]
    build:
      if: github.event_name != 'pull_request'
      uses: ./.github/workflows/build.yml
      secrets:
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      needs: [quality, test]
